Update readme
arigato-java/RealJavaButton pull request #8
Opened 2017-08-20 01:02 UTC by tomari

リードミーを微妙にアップデートする提案です

2017-08-20 03:14 UTC, tobynet requested changes
ユーザーに対して誤認させる懸念のある「(CERO-A)」という表記に関して、不正競争防止法を考慮し、

・対象年齢:  全年齢(CERO-A相当)
・対象生物: 全人類

もしくは「(CERO-A)」を外すことが適当と思われます。

2017-08-20 03:15 UTC, tobynet approved these changes
適切な修正提案、ありがとうございます！

参考: [BOM (部品表) - Wikipedia](https://ja.wikipedia.org/wiki/BOM_(%E9%83%A8%E5%93%81%E8%A1%A8))

2017-08-20 05:06 UTC, tomari commented
修正しました。

2017-08-21 11:07 UTC, merged

2017-08-21 11:07 UTC, tobynet commented
Good なので取り込みました!!!!